export const themePalettes = {
  zaot: {
    text: "#1f2937",
    tint: "#6b7280",
    background: "#ffffff",
    foreground: "#000000",
    card: "#f9fafb",
    cardForeground: "#000000",
    primary: "#6b7280",
    primaryForeground: "#ffffff",
    secondary: "#e5e7eb",
    secondaryForeground: "#374151",
    muted: "#e5e7eb",
    mutedForeground: "#6b7280",
    accent: "#f59e0b",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#d1d5db",
    input: "#f3f4f6",
  },
  ocean: {
    text: "#1f2937",
    tint: "#6b7280",
    background: "#ffffff",
    foreground: "#000000",
    card: "#f9fafb",
    cardForeground: "#000000",
    primary: "#6b7280",
    primaryForeground: "#ffffff",
    secondary: "#e5e7eb",
    secondaryForeground: "#374151",
    muted: "#e5e7eb",
    mutedForeground: "#6b7280",
    accent: "#2563eb",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#d1d5db",
    input: "#f3f4f6",
  },
  sunrise: {
    text: "#1f2937",
    tint: "#6b7280",
    background: "#ffffff",
    foreground: "#000000",
    card: "#f9fafb",
    cardForeground: "#000000",
    primary: "#6b7280",
    primaryForeground: "#ffffff",
    secondary: "#e5e7eb",
    secondaryForeground: "#374151",
    muted: "#e5e7eb",
    mutedForeground: "#6b7280",
    accent: "#ea580c",
    accentForeground: "#ffffff",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    border: "#d1d5db",
    input: "#f3f4f6",
  },
};

export const defaultThemeKey = "zaot";
export type ThemeKey = keyof typeof themePalettes;
export const radius = 12;

export default themePalettes[defaultThemeKey];
